### PR TITLE
Wide Body Fuselage Model

### PR DESCRIPTION
**Pull request by mayork**
Bjarni's wide body fuselage model

### CODE REVIEW

**Comment by whoburg** [comment]
This looks like it shares a lot with `fuselage.py`. Instead of creating a copy, how about directly editing `fuselage.py` (on the branch) to generalize it to widebody?

**Comment by mayork** [comment]
the plan was that @bjarni177 was going to edit `wide_body_fuselage.py`, which is currently a copy of `fuselage.py`, to create the wide body model. Are you saying he should just directly edit `fuselage.py` and rename once the model is complete?

**Comment by mayork** [comment]
@bjarni177 change of plans. I talked to Woody and understand what he was saying. Just edit the `fuselage.py` file. Allow it to run in two modes, narrow and wide body (just an if else statement that changes which constraints are used). This will also make it easier to track any model improvements you make to the fuselage.

**Comment by bjarni177** [comment]
I agree.

**Comment by mayork** [comment]
@pgkirsch is your fuselage model where do you assume the beams are located under the passenger floor (i.e. how far from the center)?

**Comment by pgkirsch** [comment]
I'm afraid I can't remember, but it will be whatever the TASOPT 2.08 documentation says.

**Comment by mayork** [comment]
now in the D8 repo

**Pull request closed without merging**
