### PR TITLE
Add shopping to external tests

### PR DESCRIPTION
**Pull request by lochieferrier**

### CODE REVIEW

**Comment by bqpd** [comment]
@galbramc, a new remote repo approaches!

@lochieferrier, I'll test this locally and add it to gpkit models testing if it passes.

**Comment by galbramc** [comment]
I'll show you how to add shopping next week when we are in the office. I'll be in all week starting on Tuesday.

**Comment by bqpd** [comment]
I'm not back in MA until late January, unfortunately!

**Comment by galbramc** [comment]
Ok, let me know if you want me to setup the testing or wait.

**Comment by bqpd** [comment]
This one can probably wait.

**Comment by galbramc** [comment]
Ok. I'm gone the 2nd week of January. So stop by when you are back.

**Pull request merged**
