### PR TITLE
Simple commercial flight profile

### PR DESCRIPTION
**Pull request by mayork**
still a work in progress, requires a few minor touch ups
- fix bug when each flight segment isn't the same size
- fix bug where it is dual infeasible with climb range counting towards the total flight range
- rename the atm file

### CODE REVIEW

**Comment by mayork** [comment]
@whoburg here's the simple model in a PR. I'd say its ready for an initial review, but there's still a few things to take care of.

**Comment by mayork** [comment]
@whoburg ready for review. I addressed what was discussed yesterday. The file is `Commercial_Flight_Profile_Simple.py`.

**Comment by mayork** [comment]
@pgkirsch I'm going to start linking susbystems from your thesis into the simple flight profile code and running some sweeps, I'll send you what I get for your paper

**Comment by pgkirsch** [comment]
Awesome, this is sweet!

**Comment by mayork** [comment]
there's a few other more advanced flight profiles..the end goal is to link your whole thesis with the advanced flight profile and engine

**Comment by mayork** [comment]
@whoburg this is ready for review. I plan on using this to link in with the engine code for the paper. Review commit 703af95, the last two commits are sup changes superfluous.

This will not run on master right now, I think fast subinplace introduced a bug (https://github.com/hoburg/gpkit/issues/914) but it does run on master commit ea9c127aa996dd7c1803661d1234e12f926dd646 or anything prior

**Comment by whoburg** [comment]
@mayork sorry I failed on reviewing this. Looks like there is a conflict currently. Is this still in need of review or are you updating the branch?

**Comment by mayork** [comment]
@whoburg updating to use the new performance modeling style, once the question I asked yesterday is resolved I'll branch that off and push it. I'd rather you review that code than this.

**Comment by whoburg** [comment]
Sounds good

**Comment by whoburg** [comment]
@mayork, should this be closed, or is it still in progress?

**Comment by mayork** [comment]
@whoburg the simple flight profile is done and works well. It's integrated into the D8 code, but if there is interest in having it merged into gpkit-models I can pull over the code that uses set up and vectorizes and post it for review

**Comment by whoburg** [comment]
let's keep it with the rest of the D8 code

**Pull request closed without merging**
