### PR TITLE
initial try at HALE gas powered model

### PR DESCRIPTION
**Pull request by mjburton11**
This is a model for a high altitude vehicle that uses gas as it's energy source.  Breguet range is the underlying model for time on station.

### CODE REVIEW

**Comment by mjburton11** [comment]
Hey @whoburg I added a sketchy power vs. weight that we made here (based on small honda engine models): `https://docs.google.com/spreadsheets/d/15_bX0Ub71fxrkyj72nUteMgjKj_mJw72Qi2RW3fag0I/edit?usp=sharing. `

`eta_t` is my throttle variable because I figured that `P_shaft` would only be some percentage of the max power, which is what we graphed.  

What do you think of this approach? Should we expand our engine database to include higher hp engines? Would appreciate any help.

**Comment by mjburton11** [comment]
@whoburg just added a wind model and update the power weight curve.  This could be useful to look at in class today.  I'm send the files that have the wind curves and power vs weight curves to Oren, Reo and Kelly

**Comment by bqpd** [comment]
(great to see these!)

**Comment by whoburg** [comment]
This is great! Added a commit moving the model to a .py file for better tracking of diffs in git; there's also a .ipynb alongside to run the model.

**Comment by whoburg** [comment]
Also @mjburton11 I would recommend looking at the data sheet Prof. Drela sent for gas engine sizing.

**Pull request merged**
