### PR TITLE
adding turbofan repository to external tests

### PR DESCRIPTION
**Pull request by mayork**
@bqpd should be ready to merge

### CODE REVIEW

**Comment by bqpd** [comment]
Will merge once we've 1) created the push/PR jenkins jobs for this, and 2) it's passing those.

**Comment by bqpd** [comment]
Jenkins is ready, now the tests are just waiting on a syntax failure!

**Comment by mayork** [comment]
where is the syntax error occurring? I'm a little confused because when I run `runtests.sh` everything passes without an issue.

**Comment by bqpd** [comment]
If you look at the error in https://acdl.mit.edu/csi/job/gpkit_ResearchModel_turbofan_Push/5/buildnode=macys,optimizer=cvxopt/parsed_console/, it says `Couldn't parse '/Users/jenkins/workspace/gpkit_ResearchModel_turbofan_Push/buildnode/macys/optimizer/cvxopt/Fan_LPC.py' as Python source: 'invalid syntax' at line 9`

**Comment by mayork** [comment]
oh weird that's an old file that shouldn't be used. do the tests try and compile every file or something?

**Comment by bqpd** [comment]
Yeah, so that we can say what % of python lines in the repository are run by the tests.

**Comment by bqpd** [comment]
If it's an old file, maybe remove it?

**Comment by bqpd** [comment]
Or just change the extension to `.py.old` or something.

**Comment by mayork** [comment]
ah okay. there's a lot of old files i need to remove. i'll sort through them all and let you know when i think it's done.

**Comment by mayork** [comment]
@bqpd i have all the turbofan code in a ready to review state and the tests pass so I would like to merge this

**Comment by bqpd** [comment]
Confirmed!

**Pull request merged**
